### PR TITLE
Cleaned Fixie configuration

### PR DESCRIPTION
**Pull request by siberianguy**
I'm not sure about this one but wanted to share it.

At first, I wanted to clean the Convetion classes a little bit (remove code duplication, reuse defaults). But then I found out we don't have any need for FixturePerClassConvention as all our integration tests should be cleaned per test method. On the one hand, it would be nice to keep FixturePerClassConvention just to show this approach. On the other hand, by having something that is not used, we confuse code explorers (at least I was confused about it). So for now I just removed both of them and created one tiny beautiful convention. Another alternative would be to keep both conventions but then provide some kind of test class for "per class" approach. But I can't think of any.

### CODE REVIEW

**Comment by siberianguy** [comment]
Hey, Jimmy! Any thoughts on this? :)

**Comment by jbogard** [comment]
Switched to xunit sorry man :(

**Comment by siberianguy** [comment]
No worries :) Can you elaborate why you made this decision? Was it just lack of .NET Core support from Fixie or there's something you don't like about it in general?

**Comment by jbogard** [comment]
.NET Core and xunit has complete tooling support. There wasn't anything special in Fixie that I was taking advantage of. So little if any benefits, several drawbacks.

**Comment by siberianguy** [comment]
Ok, fair enough. My instinct is to defend Fixie: it's a cute little thing after all. Don't be rude to Fixie! ;)

**Pull request closed without merging**
